# geodesic_groups_file 2.1
            #
            # Group Stuff
            #

            proc group_autoload {} {
            global gFilenames
            set grpdir $gFilenames(groups_dir)
   group_readProfiles {R_antrb_b1} [file join $grpdir {R_antrb_b1}]
   group_readProfiles {R_antrb} [file join $grpdir {R_antrb}]
   group_readProfiles {L_incrd_b14} [file join $grpdir {L_incrd_b14}]
   group_readProfiles {L_incrd_b15} [file join $grpdir {L_incrd_b15}]
   group_readProfiles {L_incrd_b12} [file join $grpdir {L_incrd_b12}]
   group_readProfiles {L_incrd_b13} [file join $grpdir {L_incrd_b13}]
   group_readProfiles {L_incrd_b10} [file join $grpdir {L_incrd_b10}]
   group_readProfiles {L_incrd_b11} [file join $grpdir {L_incrd_b11}]
   group_readProfiles {R_antrb_b2} [file join $grpdir {R_antrb_b2}]
   group_readProfiles {R_incrd_b11} [file join $grpdir {R_incrd_b11}]
   group_readProfiles {R_incrd_b10} [file join $grpdir {R_incrd_b10}]
   group_readProfiles {R_incrd_b12} [file join $grpdir {R_incrd_b12}]
   group_readProfiles {L_antrb_b2} [file join $grpdir {L_antrb_b2}]
   group_readProfiles {L_antrb} [file join $grpdir {L_antrb}]
   group_readProfiles {L_antrb_b1} [file join $grpdir {L_antrb_b1}]
   group_readProfiles {R_pcoma} [file join $grpdir {R_pcoma}]
   group_readProfiles {R_vtbrl} [file join $grpdir {R_vtbrl}]
   group_readProfiles {L_vtbrl_ppst} [file join $grpdir {L_vtbrl_ppst}]
   group_readProfiles {L_vtbrl_pre} [file join $grpdir {L_vtbrl_pre}]
   group_readProfiles {L_incrd_b1} [file join $grpdir {L_incrd_b1}]
   group_readProfiles {L_incrd} [file join $grpdir {L_incrd}]
   group_readProfiles {L_incrd_b3} [file join $grpdir {L_incrd_b3}]
   group_readProfiles {L_incrd_b2} [file join $grpdir {L_incrd_b2}]
   group_readProfiles {L_incrd_b5} [file join $grpdir {L_incrd_b5}]
   group_readProfiles {L_incrd_b4} [file join $grpdir {L_incrd_b4}]
   group_readProfiles {L_incrd_b7} [file join $grpdir {L_incrd_b7}]
   group_readProfiles {L_incrd_b6} [file join $grpdir {L_incrd_b6}]
   group_readProfiles {L_incrd_b9} [file join $grpdir {L_incrd_b9}]
   group_readProfiles {R_vtbrl_b1} [file join $grpdir {R_vtbrl_b1}]
   group_readProfiles {R_vtbrl_b2} [file join $grpdir {R_vtbrl_b2}]
   group_readProfiles {R_vtbrl_b3} [file join $grpdir {R_vtbrl_b3}]
   group_readProfiles {R_vtbrl_b4} [file join $grpdir {R_vtbrl_b4}]
   group_readProfiles {R_vtbrl_b5} [file join $grpdir {R_vtbrl_b5}]
   group_readProfiles {R_vtbrl_b6} [file join $grpdir {R_vtbrl_b6}]
   group_readProfiles {R_vtbrl_b7} [file join $grpdir {R_vtbrl_b7}]
   group_readProfiles {R_incrd_b8} [file join $grpdir {R_incrd_b8}]
   group_readProfiles {R_incrd_b9} [file join $grpdir {R_incrd_b9}]
   group_readProfiles {R_incrd_b2} [file join $grpdir {R_incrd_b2}]
   group_readProfiles {R_incrd_b3} [file join $grpdir {R_incrd_b3}]
   group_readProfiles {R_incrd} [file join $grpdir {R_incrd}]
   group_readProfiles {R_incrd_b1} [file join $grpdir {R_incrd_b1}]
   group_readProfiles {R_incrd_b6} [file join $grpdir {R_incrd_b6}]
   group_readProfiles {R_incrd_b7} [file join $grpdir {R_incrd_b7}]
   group_readProfiles {R_incrd_b4} [file join $grpdir {R_incrd_b4}]
   group_readProfiles {R_incrd_b5} [file join $grpdir {R_incrd_b5}]
   group_readProfiles {L_vtbrl_b4} [file join $grpdir {L_vtbrl_b4}]
   group_readProfiles {L_vtbrl_b5} [file join $grpdir {L_vtbrl_b5}]
   group_readProfiles {L_incrd_b8} [file join $grpdir {L_incrd_b8}]
   group_readProfiles {L_vtbrl_b1} [file join $grpdir {L_vtbrl_b1}]
   group_readProfiles {L_vtbrl_b2} [file join $grpdir {L_vtbrl_b2}]
   group_readProfiles {L_vtbrl_b3} [file join $grpdir {L_vtbrl_b3}]
   group_readProfiles {L_pcoma} [file join $grpdir {L_pcoma}]
}